### ISSUE TITLE
publish sdk to sonatype central

### ISSUE THREAD

**Issue by strantalis** [opentdf/java-sdk#79]
We should look to move off of github packages to support anonymous reads. I started this pr a while back but it required more work than expected to get setup. 

https://github.com/opentdf/java-sdk/pull/25

See https://virtru.atlassian.net/wiki/spaces/ENG/pages/3543105546/Maven+Central+Sonatype

**Comment by mustyantsev** [comment]
CAB ticket [(https://virtru.atlassian.net/browse/CAB-3105)]

**Comment by pflynn-virtru** [comment]
new draft PR https://github.com/opentdf/java-sdk/pull/165

**Comment by pflynn-virtru** [comment]
updating to use Maven Central latest plugins instead of OSSRH
